apiVersion: apps/v1
kind: Deployment
metadata:
  name: carduka-deployment
  labels:
    app: carduka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carduka
  template:
    metadata:
      labels:
        app: carduka
    spec:
      containers:
        - name: carduka
          image: carduka:1.0.2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: carduka-config
            - secretRef:
                name: carduka-secret

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m" #CPU in Kubernetes can be written in millicores where 1000m = 1 CPU core, so we give 0.25 CPU core
            limits:
              memory: "512Mi" #If Carduka exceeds around 512Mi memory, Kubernetes may kill and restart the container.
              cpu: "500m"

          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3